# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  workflow_call:
    inputs: 
      deployTarget:
        required: true
        type: string
        
  workflow_dispatch:
    inputs: 
      deployTarget:
        description: Select the environment to deploy
        required: true
        type: environment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy ${{ github.event.inputs.deployTarget }}
    # Attempt to set the environment for the job and thus trigger a github.deployment to this environment.
    environment: ${{ github.event.inputs.deployTarget }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: set vars for workflow_dispatch
        run: echo "computedDeployTarget=${{ github.event.inputs.deployTarget }}"
        if: ${{ github.event.inputs.deployTarget != null }}


      - name: set vars for workflow_call
        run: echo "computedDeployTarget=${{ inputs.deployTarget }}"
        if: ${{ inputs.deployTarget != null }}


      - name: Echo Deploy Context
        run: |
          echo workflow_dispatch context deployTaget was '${{ github.event.inputs.deployTarget }}'
          echo workflow_call context deployTaget was '${{ inputs.deployTarget }}'
          echo deployContext to use is: ${{ env.computedDeployTarget }}
